-- Survey responses table schema
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS survey_responses (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id text NOT NULL UNIQUE,
  survey_version text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  started_at timestamptz DEFAULT timezone('utc'::text, now()),
  completed_at timestamptz,
  current_section text DEFAULT 'demographics',
  progress_percentage integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  time_spent_seconds integer DEFAULT 0,
  user_agent text,
  ip_address text,
  referrer_url text,
  email text NOT NULL,
  company_name text,
  industry text,
  industry_other text,
  role text,
  role_other text,
  unit_count text,
  annual_revenue text,
  personal_ai_usage text,
  org_ai_usage text,
  ai_usage_change text,
  ai_tools text[],
  ai_tools_industry_specific text,
  ai_tools_custom text,
  ai_tools_other text,
  primary_ai_tool text,
  ai_use_cases text[],
  ai_use_cases_other text,
  corporate_ai_matrix jsonb,
  franchisee_ai_support text,
  franchisee_support_methods text[],
  franchisee_support_methods_other text,
  franchisee_adoption_rate text,
  franchisee_ai_learning text[],
  franchisee_ai_learning_other text,
  annual_ai_budget text,
  ai_budget_change text,
  ai_investment_decision_maker text,
  ai_investment_decision_maker_other text,
  measured_roi text,
  measured_improvements text[],
  measured_improvements_other text,
  challenges_ranked text[],
  challenges_other text,
  dedicated_ai_expertise text,
  data_infrastructure_readiness integer,
  centralized_data_platform text,
  data_sources text[],
  data_sources_other text,
  customer_facing_ai text,
  customer_ai_interactions text[],
  customer_ai_interactions_other text,
  customer_feedback text,
  greatest_ai_potential text,
  greatest_ai_potential_other text,
  increase_ai_investment_2026 text,
  adoption_accelerators text[],
  adoption_accelerators_other text,
  ai_policy text,
  ethical_concerns text[],
  ethical_concerns_other text,
  job_impact_concern integer,
  ai_for_compliance text,
  competitor_comparison text,
  exciting_ai_trend text,
  personal_ai_comfort integer,
  desired_ai_capabilities text,
  receive_report text,
  survey_feedback text,
  agntmkt_followup text,
  first_name text,
  last_name text
);
